name: Publish Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Publish and Archive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: windows
            rid: win-x64
            asset_path: publish/RadiumLauncher-Windows-x64.zip
          - target: linux
            rid: linux-x64
            asset_path: publish/RadiumLauncher-Linux-x64.tar.gz
          - target: macos
            rid: osx-arm64
            asset_path: publish/RadiumLauncher-macOS-arm64.zip

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -o publish/${{ matrix.target }}

      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full

      - name: Archive
        run: |
          if [ "${{ matrix.target }}" == "windows" ]; then
            7z a -tzip $GITHUB_WORKSPACE/${{ matrix.asset_path }} ./publish/windows/*
          elif [ "${{ matrix.target }}" == "linux" ]; then
            tar -czf $GITHUB_WORKSPACE/${{ matrix.asset_path }} -C publish/linux .
          elif [ "${{ matrix.target }}" == "macos" ]; then
            7z a -tzip $GITHUB_WORKSPACE/${{ matrix.asset_path }} ./publish/macos/*
          fi

      - name: Debug
        run: ls -la publish/${{ matrix.target }}/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets-${{ matrix.target }}
          path: ${{ matrix.asset_path }}

  release:
    name: Release GitHub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: assets-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
